server:
  port: 8800


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka-service

security:
  basic:
    enabled: false
  user:
    name: godder
    password: godder