server:
  port: 8820

spring:
  application:
    name: service-data
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${properties.database.data-service.url}:${properties.database.data-service.port}/${properties.database.data-service.database-name}?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${properties.database.data-service.username}
    password: ${properties.database.data-service.password}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      inital-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      testWhileldle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      filter:
        wall:
          enabled: true
          db-type: mysql
          log-violation: true
          throw-exception: true
          config:
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      web-stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      stat-view-servlet:
        login-username: admin
        login-password: admin

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: top.godder.dataapi.entry

security:
  user:
    name: godder
    password: godder

jwt:
  secret: godder
  token_prefix: datasharing
#  expriation_time: 604800000
